name: RankShopGUI
main: ClickedTran\rankshop\RankShopGUI
api: 5.0.0
version: 1.0.0
author: ClickedTran
virions: ["InvMenu", "FormAPI", "libPiggyEconomy", "libRanks"]

permissions:
 rankshopgui.command:
  default: true
  description: Permission for player use RankShop!
 rankshopgui.command.create:
  default: op
  description: Permission for admin or staff create new shop rank
 rankshopguu.command.remove:
  description: Permission for admin or staff remove shop rank exists
  default: op
 rankshopgui.command.edit:
  default: op
  description: Permission for admin or staff edit shop rank exists
 rankshopgui.command.help:
  default: op
